// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-hG6CYCWMq66jsucC3AnbobSR8iyHq0',
    appId: '1:329957332442:web:067e93ae526a143a349ce3',
    messagingSenderId: '329957332442',
    projectId: 'multi-translate-app',
    authDomain: 'multi-translate-app.firebaseapp.com',
    storageBucket: 'multi-translate-app.firebasestorage.app',
    measurementId: 'G-KL75W2CZB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_LDb35QhIKnS-yQ1bZprxzq8my_TddW4',
    appId: '1:329957332442:android:a7b01f3fd3cf6285349ce3',
    messagingSenderId: '329957332442',
    projectId: 'multi-translate-app',
    storageBucket: 'multi-translate-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW-hG6CYCWMq66jsucC3AnbobSR8iyHq0',
    appId: '1:329957332442:web:47a81d98420aa994349ce3',
    messagingSenderId: '329957332442',
    projectId: 'multi-translate-app',
    authDomain: 'multi-translate-app.firebaseapp.com',
    storageBucket: 'multi-translate-app.firebasestorage.app',
    measurementId: 'G-69M7CLE06N',
  );
}
